rock/project/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^rock/', include('rock.urls', namespace='rock')),
]

rock/rock/urls.py
from django.conf.urls import url
from rock import views
urlpatterns = [
    url(r'^home/', views.Home,name='home'),
    url(r'^home_logined/', views.Home_logined, name='home_logined'),
    url(r'^home_logined_collected/', views.Home_logined_collected, name='home_logined_collected'),
    url(r'^login/', views.Login, name='login'),
    url(r'^register/', views.Register, name='register'),
    url(r'^userinfo_mod/', views.Userinfo_mod, name='userinfo_mod'),
    url(r'^collected/',views.Collected,name="collected"),
    url(r'^delcollected/', views.delCollected, name="delcollected"),
]

rock/rock/models.py
from django.db import models

class userinfo(models.Model):
    username = models.CharField(max_length=32,null = True)
    password = models.CharField(max_length=64,null = True)
    email = models.CharField(max_length = 32,null = True)
    class Meta:
        db_table = 'userinfo'

class movies(models.Model):
    name = models.CharField(max_length=64,null = True)
    detail = models.CharField(max_length=64,null = True)
    Img = models.CharField(max_length = 256,null = True)
    time = models.CharField(max_length=16,null=True)
    class Meta:
        db_table = 'movies'

class collected(models.Model):
    user_list = models.ForeignKey(to='userinfo',db_column='uid')
    movie_list = models.ForeignKey(to='movies',db_column='mid')
    class Meta:
        db_table = 'collexted'

rock/rock/views.py
from django.core import serializers
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from rock.models import userinfo  ,movies ,collected


def Home(request):

    mv = movies.objects.all()
    return render(request,'rock/home.html',{'movi':mv})
def Home_logined(request):
    username = request.session.get("username")
    data = {
        "username": username
    }
    mv = movies.objects.all()
    userid = userinfo.objects.filter(username=username).first().id
    cid = collected.objects.filter(user_list_id=userid).all()
    list_m = []
    for i in cid:
        print(i.movie_list_id)
        mid = i.movie_list_id
        list_m.append(mid)

    for j in mv:
        print(j.id)
    return render(request,'rock/home_logined.html',{"data":data,'movi':mv,'list':list_m})
def Home_logined_collected(request):
    username = request.session.get("username")
    uata = {
        "username": username
    }
    mata = movies.objects.all()
    userid = userinfo.objects.filter(username=username).first().id
    cid = collected.objects.filter(user_list_id=userid).all()
    list_m = []
    for i in cid:
        print(i.movie_list_id)
        mid = i.movie_list_id
        list_m.append(mid)
    return render(request,'rock/home_logined_collected.html',{'data':list_m,"mata":mata,'uata':uata})
def Login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        userobj = userinfo.objects.filter(username=username).first()
        passwd = userobj.password

        print(userobj,username,password)

        if userobj:
            if password == passwd:
             request.session['username'] = username
            return redirect('/rock/home_logined/')
        else:
            return render(request, 'rock/login.html')
    return render(request,'rock/login.html')
def Register(request):
    if request.method=="POST":
        from rock.models import userinfo
        username = request.POST.get('username')
        password = request.POST.get('password')
        password1 = request.POST.get('password1')
        email = request.POST.get('email')
        userobj = userinfo.objects.filter(username=username)
        if userobj:
            return HttpResponse("用户已存在")
        else:
            if password !=password1:
                return HttpResponse("密码输入有误")
            userinfo.objects.create(
                username=username,
                password=password,
                email=email,
            )
            return render(request,'rock/login.html')
    return render(request,'rock/register.html')
def Userinfo_mod(request):
    if request.method == "GET":

        account = request.session.get("username")
        userobj = userinfo.objects.filter(username=account).values('username','email')
        return render(request, 'rock/userinfo_mod.html', {"data": userobj})
    if request.method == "POST":
        account = request.session.get("username")
        username = request.POST.get("username")
        password = request.POST.get("password")
        email = request.POST.get("email")
        userinfo.objects.filter(username=account).update(username=username,password=password,email=email)
        return HttpResponseRedirect(reverse('rock:home'))

def Collected(request):
    mid = request.POST.get('pk')
    account = request.session.get('username')
    uid = userinfo.objects.filter(username=account).first()
    collected.objects.create(
        movie_list_id=mid,
        user_list=uid
    )
    return HttpResponseRedirect(reverse('rock:home_logined_collected'))


def delCollected(request):
    mid = request.POST.get('pk')
    account = request.session.get('username')
    uid = userinfo.objects.filter(username=account).first()
    collected.objects.filter(movie_list=mid,user_list=uid).delete()
    return HttpResponseRedirect(reverse('rock:home_logined_collected'))

rock/templates/rock/home.html
<!DOCTYPE html>
<html>

	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

		<script type="text/javascript" src="/static/rock/js/jquery.js"></script>
		<script type="text/javascript" src="/static/rock/js/bootstrap.js"></script>
		<link rel="stylesheet" href="/static/rock/css/bootstrap.css" />
		<link rel="stylesheet" type="text/css" href="/static/rock/css/bootstrap-theme.css" />
		<link rel="stylesheet" type="text/css" href="/static/rock/css/swiper.css" />
		<script type="text/javascript" src="/static/rock/js/swiper.js"></script>
		<link rel="stylesheet" type="text/css" href="/static/rock/css/reset.css" />

		<link rel="stylesheet" type="text/css" href="/static/rock/css/home.css"/>
		<script type="text/javascript" src="/static/rock/js/home.js" ></script>
	</head>

	<body>

		<div class="container-fluid">

			<nav class="navbar navbar-inverse">
				<div class="container-fluid">
					<div class="navbar-header">
						<a class="navbar-brand" href="#">Rock</a>
					</div>
					<ul class="nav navbar-nav navbar-right">
						<li>
							<a href="{% url "rock:register" %}">注册</a>
						</li>
						<li>
							<a href="{% url "rock:login" %}">登陆</a>
						</li>
						<!--<li>
							<a class="icon" href="#">
								<img width="40" height="40" class="img-circle" alt="" src="https://cs.vmovier.com/Uploads/Banner/2017/12/23/5a3d52d82724d.png" />
							</a>
						</li>

						<li>
							<a href=""><span>Username</span></a>
						</li>-->
					</ul>
				</div>

			</nav>

			<div class="swiper-container">
				<div class="swiper-wrapper">
					<div class="swiper-slide">
						<img src="https://cs.vmovier.com/Uploads/Banner/2017/12/23/5a3d52d82724d.png" alt="">
					</div>

					<div class="swiper-slide">
						<img src="https://cs.vmovier.com/Uploads/Banner/2017/12/18/5a379a0c4bff3.jpg" alt="">
					</div>
				</div>
				<!-- Add Pagination -->
				<div class="swiper-pagination swiper-pagination-white"></div>
				<!-- Add Arrows -->
				<div class="swiper-button-next swiper-button-white"></div>
				<div class="swiper-button-prev swiper-button-white"></div>
			</div>

			<ul class="nav nav-tabs child-nav">
				<li role="presentation" class="active">
					<a href="#">最新推荐</a>
				</li>
				<!--<li role="presentation">
					<a href="#">收藏</a>
				</li>-->

			</ul>


			<ul class="movie_list">
				{% for item in movi %}
				<li>
					<div class="movie_list_left">
						<a target="_blank" href="#" title="{{ item.name }}">
							<img src="{{ item.Img }}" alt="{{ item.name }}">
							<div class="bottom-cover">
								<span class="film-time">{{ item.time }}</span>
							</div>
						</a>
					</div>

					<div class="movie_list_right">
						<h2>
							<a target="_blank" href="" title="{{ item.name }}">
								<span>{{ item.name }}</span>
							</a>
						</h2>

						<div class="movie-intro">
							{{ item.detail }}
						</div>
						<div class="movie-like">

                                <span class="glyphicon glyphicon-heart" style="color: gray;"></span>

							<span>200</span>
						</div>
					</div>
				</li>
                {% endfor %}

			</ul>

		</div>

	</body>

</html>

rock/templates/rock/home_logined.html
<!DOCTYPE html>
<html>

	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

		<script type="text/javascript" src="/static/rock/js/jquery.js"></script>
		<script type="text/javascript" src="/static/rock/js/bootstrap.js"></script>
		<link rel="stylesheet" href="/static/rock/css/bootstrap.css" />
		<link rel="stylesheet" type="text/css" href="/static/rock/css/bootstrap-theme.css" />
		<link rel="stylesheet" type="text/css" href="/static/rock/css/swiper.css" />
		<script type="text/javascript" src="/static/rock/js/swiper.js"></script>
		<link rel="stylesheet" type="text/css" href="/static/rock/css/reset.css" />

		<link rel="stylesheet" type="text/css" href="/static/rock/css/home.css"/>
		<script type="text/javascript" src="/static/rock/js/home.js" ></script>
	</head>

	<body>

		<div class="container-fluid">

			<nav class="navbar navbar-inverse">
				<div class="container-fluid">
					<div class="navbar-header">
						<a class="navbar-brand" href="#">Rock</a>
					</div>
					<ul class="nav navbar-nav navbar-right">
						<!--<li>
							<a href="#">注册</a>
						</li>
						<li>
							<a href="#">登陆</a>
						</li>-->
						<li>
							<a class="icon" href="#">
								<img width="40" height="40" class="img-circle" alt="" src="https://cs.vmovier.com/Uploads/Banner/2017/12/23/5a3d52d82724d.png" />
							</a>
						</li>

						<li>
							<a href="/rock/userinfo_mod/"><span>{{ data.username }}</span></a>
						</li>
					</ul>
				</div>

			</nav>

			<div class="swiper-container">
				<div class="swiper-wrapper">
					<div class="swiper-slide">
						<img src="https://cs.vmovier.com/Uploads/Banner/2017/12/23/5a3d52d82724d.png" alt="">
					</div>

					<div class="swiper-slide">
						<img src="https://cs.vmovier.com/Uploads/Banner/2017/12/18/5a379a0c4bff3.jpg" alt="">
					</div>
				</div>
				<!-- Add Pagination -->
				<div class="swiper-pagination swiper-pagination-white"></div>
				<!-- Add Arrows -->
				<div class="swiper-button-next swiper-button-white"></div>
				<div class="swiper-button-prev swiper-button-white"></div>
			</div>

			<ul class="nav nav-tabs child-nav">
				<li role="presentation" class="active">
					<a>最新推荐</a>
				</li>
				<li role="presentation">
					<a href="/rock/home_logined_collected/">收藏</a>
				</li>

			</ul>


			<ul class="movie_list">
                {% for item in movi %}

                        <li>
                            <div class="movie_list_left">
                                <a target="_blank" href="#" title="{{ item.name }}">
                                    <img src="{{ item.Img }}" alt="{{ item.name }}">
                                    <div class="bottom-cover">
                                        <span class="film-time">{{ item.time }}</span>
                                    </div>
                                </a>
                            </div>
                            <div class="movie_list_right">
                                <h2>
                                    <a target="_blank" href="" title="{{ item.name }}">
                                        <span>{{ item.name }}</span>
                                    </a>
                                </h2>
                                <div class="movie-intro">
                                    {{ item.detail }}
                                </div>
                                <form action="/rock/collected/" method="post">
                                {% for i in list %}
                                    <div class="movie-like">
                                        <input type="hidden" name="pk" value="{{ item.id }}">
                                            {% ifequal item.id i %}
                                            <span class="glyphicon glyphicon-heart" style="color: red;"></span>
                                            {% endifequal %}
                                            {% ifnotequal item.id i %}
                                            <span class="glyphicon glyphicon-heart" style="color: gray;"></span>
                                            {% endifnotequal %}
                                        <span>200</span>
                                        <input type="submit" value="收藏">
                                    </div>
                                {% endfor %}
                                </form>
                            </div>
                        </li>
                {% endfor %}

			</ul>

		</div>

	</body>

</html>

rock/templates/rock/home_logined_collected.html
<!DOCTYPE html>
<html>

	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

		<script type="text/javascript" src="/static/rock/js/jquery.js"></script>
		<script type="text/javascript" src="/static/rock/js/bootstrap.js"></script>
		<link rel="stylesheet" href="/static/rock/css/bootstrap.css" />
		<link rel="stylesheet" type="text/css" href="/static/rock/css/bootstrap-theme.css" />
		<link rel="stylesheet" type="text/css" href="/static/rock/css/swiper.css" />
		<script type="text/javascript" src="/static/rock/js/swiper.js"></script>
		<link rel="stylesheet" type="text/css" href="/static/rock/css/reset.css" />

		<link rel="stylesheet" type="text/css" href="/static/rock/css/home.css"/>
		<script type="text/javascript" src="/static/rock/js/home.js" ></script>
		<style type="text/css">
			.movie-like span{
				color: red;
			}
		</style>
	</head>

	<body>

		<div class="container-fluid">

			<nav class="navbar navbar-inverse">
				<div class="container-fluid">
					<div class="navbar-header">
						<a class="navbar-brand" href="#">Rock</a>
					</div>
					<ul class="nav navbar-nav navbar-right">
						<!--<li>
							<a href="#">注册</a>
						</li>
						<li>
							<a href="#">登陆</a>
						</li>-->
						<li>
							<a class="icon" href="#">
								<img width="40" height="40" class="img-circle" alt="" src="https://cs.vmovier.com/Uploads/Banner/2017/12/23/5a3d52d82724d.png" />
							</a>
						</li>

						<li>
							<a href=""><span>{{ uata.username }}</span></a>
						</li>
					</ul>
				</div>

			</nav>

			<div class="swiper-container">
				<div class="swiper-wrapper">
					<div class="swiper-slide">
						<img src="https://cs.vmovier.com/Uploads/Banner/2017/12/23/5a3d52d82724d.png" alt="">
					</div>

					<div class="swiper-slide">
						<img src="https://cs.vmovier.com/Uploads/Banner/2017/12/18/5a379a0c4bff3.jpg" alt="">
					</div>
				</div>
				<!-- Add Pagination -->
				<div class="swiper-pagination swiper-pagination-white"></div>
				<!-- Add Arrows -->
				<div class="swiper-button-next swiper-button-white"></div>
				<div class="swiper-button-prev swiper-button-white"></div>
			</div>

			<ul class="nav nav-tabs child-nav">
				<li role="presentation" >
					<a href="/rock/home_logined/">最新推荐</a>
				</li>
				<li role="presentation" class="active">
					<a>收藏</a>
				</li>

			</ul>
			<ul class="movie_list">
            {% for item in mata %}
				{% for i in data %}
                    {% ifequal i item.id %}


                        <li>
                            <div class="movie_list_left">
                                <a target="_blank" href="#" title="{{ item.name }}">
                                    <img src="{{ item.Img }}" alt="{{ item.name }}">
                                    <div class="bottom-cover">
                                        <span class="film-time">{{ item.time }}</span>
                                    </div>
                                </a>
                            </div>

                            <div class="movie_list_right">
                                <h2>
                                    <a target="_blank" href="" title="{{ item.name }}">
                                        <span>{{ item.name }}</span>
                                    </a>
                                </h2>

                                <div class="movie-intro">
                                    {{ item.detail }}
                                </div>
                                <form action="/rock/delcollected/" method="post">
                                <div class="movie-like">
                                        <input type="hidden" name="pk" value="{{ item.id }}">
                                        <span class="glyphicon glyphicon-heart" style="color: red;"></span>
                                    <span>200</span>
                                    <input type="submit" value="取消收藏">
                                </div>
                                </form>
                            </div>
                        </li>

                    {% endifequal %}
                {% endfor %}
            {% endfor %}

			</ul>

		</div>

	</body>

</html>

rock/templates/rock/login.html
<!DOCTYPE html>
<html>

	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

		<script type="text/javascript" src="/static/rock/js/jquery.js"></script>
		<script type="text/javascript" src="/static/rock/js/bootstrap.js"></script>
		<link rel="stylesheet" href="/static/rock/css/bootstrap.css" />
		<link rel="stylesheet" type="text/css" href="/static/rock/css/bootstrap-theme.css" />

		<link rel="stylesheet" type="text/css" href="/static/rock/css/swiper.css" />
		<script type="text/javascript" src="/static/rock/js/swiper.js"></script>
		<link rel="stylesheet" type="text/css" href="/static/rock/css/reset.css" />
		<style type="text/css">
			.form-info {
				border: 1px solid orange;
				margin: 100px auto;
				width: 30%;
				padding: 50px;
			}
			
			.form-info h2 {
				font-size: 2rem;
				margin-bottom: 20px;
			}
			
			.form-info .submit {
				text-align: center;
			}
		</style>
	</head>

	<body>

		<div class="container-fluid">
			<div class="form-info">

				<h2>用户登陆</h2>

				<form action="/rock/login/" method="post">
					<div class="form-group">
						<label for="exampleInputEmail1">用户名</label>
						<input type="text" class="form-control" id="exampleInputEmail1" name="username" placeholder="请输入用户名">
						<p class="help-block">请输入6-16位用户名</p>
					</div>
					<div class="form-group">
						<label for="exampleInputPassword1">密码</label>
						<input type="password" class="form-control" name="password" placeholder="请输入密码">
						<p class="help-block">请输入6位以上拼音字母组合密码</p>
					</div>

					<div class="submit"><button type="submit" class="btn btn-primary">登陆</button></div>

				</form>
			</div>
		</div>

	</body>

</html>

rock/templates/rock/register.html
<!DOCTYPE html>
<html>

	<head>
		<meta charset="UTF-8">
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

		<script type="text/javascript" src="/static/rock/js/jquery.js"></script>
		<script type="text/javascript" src="/static/rock/js/bootstrap.js"></script>
		<link rel="stylesheet" href="/static/rock/css/bootstrap.css" />
		<link rel="stylesheet" type="text/css" href="/static/rock/css/bootstrap-theme.css" />

		<link rel="stylesheet" type="text/css" href="/static/rock/css/swiper.css" />
		<script type="text/javascript" src="/static/rock/js/swiper.js"></script>
		<link rel="stylesheet" type="text/css" href="/static/rock/css/reset.css" />
		<style type="text/css">
			.form-info {
				border: 1px solid orange;
				margin: 100px auto;
				width: 30%;
				padding: 50px;
			}
			
			.form-info h2{
				font-size: 2rem;
				margin-bottom: 20px;
			}
			.form-info .submit{
				text-align: center;
			}
		</style>
	</head>

	<body>

		<div class="container-fluid">
			<div class="form-info">
				
				<h2>用户注册</h2>
				
				<form action="/rock/register/" method="post">
					<div class="form-group">
						<label for="exampleInputEmail1">用户名</label>
						<input type="text" class="form-control" id="exampleInputEmail1" name="username" placeholder="请输入用户名">
						<p class="help-block">请输入6-16位用户名</p>
					</div>
					<div class="form-group">
						<label for="exampleInputPassword1">密码</label>
						<input type="password" class="form-control" name="password" placeholder="请输入密码">
						<p class="help-block">请输入6位以上拼音字母组合密码</p>
					</div>
					<div class="form-group">
						<label for="exampleInputPassword1">确认密码</label>
						<input type="password" name="password1" class="form-control" placeholder="请再次输入密码">
						<p class="help-block">请再次输入6位以上拼音字母组合密码</p>
					</div>
					<div class="form-group">
						<label for="exampleInputPassword1">邮箱</label>
						<input type="password" class="form-control" name="email" placeholder="请再次输入密码">
						<p class="help-block">请输入邮箱</p>
					</div>
					<div class="form-group">
						<label for="exampleInputFile">头像</label>
						<input type="file" id="exampleInputFile" name="img">
						
					</div>
					<div class="submit"><button type="submit" class="btn btn-primary">注册</button></div>
					
				</form>
			</div>
		</div>

	</body>

</html>

rock/templates/rock/userinfo_mod.html
<!DOCTYPE html>
<html>

	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

		<script type="text/javascript" src="/static/rock/js/jquery.js"></script>
		<script type="text/javascript" src="/static/rock/js/bootstrap.js"></script>
		<link rel="stylesheet" href="/static/rock/css/bootstrap.css" />
		<link rel="stylesheet" type="text/css" href="/static/rock/css/bootstrap-theme.css" />

		<link rel="stylesheet" type="text/css" href="/static/rock/css/swiper.css" />
		<script type="text/javascript" src="/static/rock/js/swiper.js"></script>
		<link rel="stylesheet" type="text/css" href="/static/rock/css/reset.css" />
		<style type="text/css">
			.form-info {
				border: 1px solid orange;
				margin: 100px auto;
				width: 30%;
				padding: 50px;
			}
			
			.form-info h2 {
				font-size: 2rem;
				margin-bottom: 20px;
			}
			
			.form-info .submit {
				text-align: center;
			}
			
			.form-info img{
				width: 40px;
				height: 40px;
				float: left;
			}
			input[type=file]{
				float: left;
				height: 40px;
				line-height: 40px;
				padding-left: 20px;
			}
		</style>
	</head>

	<body>

		<div class="container-fluid">
			<div class="form-info">

				<h2>信息修改</h2>

				<form action="/rock/userinfo_mod/" method="post">
                    {% for item in data %}
					<div class="form-group">
						<label for="exampleInputEmail1">用户名</label>
						<input type="text" class="form-control" id="exampleInputEmail1" name="username" placeholder="请输入用户名" value="{{ item.username }}" >
					</div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">密码</label>
                        <input type="text" class="form-control" id="exampleInputEmail1" name="password" placeholder="请输入密码" value="" >
					</div>
					<div class="form-group">
						<label for="exampleInputPassword1">邮箱</label>
						<input type="email" class="form-control"  name="email" placeholder="请输入新的邮箱" value="{{ item.email }}">
					</div>
					<div class="form-group clearfix">
						<label for="exampleInputFile">头像</label><br />
						<img class="img-circle" src="https://cs.vmovier.com/Uploads/Banner/2017/12/23/5a3d52d82724d.png" alt="" /> 
						<input type="file" name="img" id="exampleInputFile">
					</div>
                    {% endfor %}
					<div class="submit"><button type="submit" class="btn btn-primary">提交</button></div>

				</form>
			</div>
		</div>

	</body>

</html>